[package]
name = "git-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
crossterm = "0.28.1"
fuzzy-matcher = "0.3.7"
log = "0.4.26"
simplelog = "0.12.2"
